name: Auto TWRP Device Tree Generator

on:
  workflow_dispatch:
    inputs:
      IMG_URL:
        description: 'URL of boot or recovery image (.img)'
        required: true
      DEVICE_BRAND:
        description: 'Device manufacturer (e.g., xiaomi, samsung)'
        required: true
      CODENAME:
        description: 'Device codename (e.g., daisy, gale)'
        required: true
      GIT_NAME:
        description: 'GitHub username'
        required: true
      GIT_EMAIL:
        description: 'GitHub email'
        required: true

jobs:
  generate-tree:
    name: Generate and Push TWRP Device Tree
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest

    env:
      IMG_URL: ${{ github.event.inputs.IMG_URL }}
      DEVICE_BRAND: ${{ github.event.inputs.DEVICE_BRAND }}
      CODENAME: ${{ github.event.inputs.CODENAME }}
      GIT_NAME: ${{ github.event.inputs.GIT_NAME }}
      GIT_EMAIL: ${{ github.event.inputs.GIT_EMAIL }}
      GH_TOKEN: ${{ secrets.TWRP_PUSH }}

    permissions:
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y git python3 python3-pip cpio aria2 gh
        pip3 install --upgrade twrpdtgen

    - name: Download Image File
      run: |
        mkdir -p ~/TWRP-Tree
        cd ~/TWRP-Tree
        aria2c "$IMG_URL" -o input.img

    - name: Generate TWRP Device Tree
      run: |
        cd ~/TWRP-Tree
        python3 -m twrpdtgen -o output input.img

    - name: Configure Git Identity
      run: |
        git config --global user.name "$GIT_NAME"
        git config --global user.email "$GIT_EMAIL"

    - name: Create and Push New GitHub Repository
      run: |
        cd ~/TWRP-Tree/output
        git init
        git checkout -b twrp-12.1
        git add .
        git commit -m "$CODENAME: Initial TWRP tree generated by twrpdtgen"

        gh auth login --with-token <<< "$GH_TOKEN"

        NEW_REPO="twrp_device_${DEVICE_BRAND}_${CODENAME}"
        gh repo create "$GIT_NAME/$NEW_REPO" --public --description "TWRP device tree for $CODENAME" --source=. --remote=origin --push

        git push -u origin twrp-12.1 --force

    - name: Done
      run: echo "✅TWRP device tree pushed to https://github.com/${{ github.event.inputs.GIT_NAME }}/twrp_device_${{ github.event.inputs.DEVICE_BRAND }}_${{ github.event.inputs.CODENAME }}"
